--Full Backup

BACKUP DATABASE ERPDB
TO DISK = 'F:\ERPSQLDB\Backup\ERPDB_Full.bak'
WITH FORMAT,
INIT,
NAME = 'ERPDB Full Backup',
STATS = 10;

--Differential Backup
BACKUP DATABASE ERPDB
TO DISK = 'F:\ERPSQLDB\Backup\ERPDB_Diff.bak'
WITH DIFFERENTIAL,
STATS = 10;


ALTER DATABASE ERPDB SET RECOVERY FULL;
GO

BACKUP LOG ERPDB
TO DISK = 'F:\ERPSQLDB\Backup\ERPDB_Log.trn'
WITH STATS = 10;
